import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1C2434',
    paddingHorizontal: 10,
    paddingTop: Platform.OS === 'android' ? 38 : 50,
    paddingBottom: 12,
    gap: 8,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F2F2',
    borderRadius: 10,
    paddingHorizontal: 8,
    height: 36,
    marginLeft: 5,
    gap: 6,
  },
  searchInput: {
    flex: 1,
    fontSize: 12,
    color: '#1C2434',
    padding: 0,
    height: 36,
  },
  personCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 120,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  emptyText: {
    fontSize: 14,
    color: '#000000',
    marginTop: 10,
    marginBottom: 20,
  },
  orderCard: {
    flexDirection: 'row',
    backgroundColor: '#E3E4EB',
    borderRadius: 15,
    marginBottom: 20,
    minHeight: 100,
    position: 'relative',
    overflow: 'visible',
    zIndex: 10,
  },
  photoCol: {
    width: 105,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  photoBox: {
    width: 80,
    height: 80,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  placeholderImg: {
    width: 70,
    height: 70,
    backgroundColor: '#EAEAEA',
  },
  numCol: {
    width: 80,
    alignItems: 'center',
    paddingTop: 15,
  },
  orderIdText: {
    fontSize: 12,
    color: '#000000',
  },
  pgtoCol: {
    width: 105,
    alignItems: 'center',
    paddingTop: 15,
  },
  pgtoText: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  actionCol: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 999,
  },
  separatorLines: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1.5,
    backgroundColor: '#F5F5F5',
  },
  dropdownBox: {
    position: 'absolute',
    top: 70,
    right: 5,
    width: 110,
    backgroundColor: '#E3E4EB',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CCC',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 2000,
  },
  dropItemBtn: {
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  dropSeparator: {
    height: 1,
    backgroundColor: '#CCC',
    marginHorizontal: 5,
  },
  tabBarOuter: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 34 : 24,
    left: 16,
    right: 16,
  },
  tabBarInner: {
    flexDirection: 'row',
    backgroundColor: '#E3E4EB',
    borderRadius: 30,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  tabSeparator: {
    width: 1,
    height: 49,
    backgroundColor: '#8A7268',
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  iconBgInactive: {
    width: 51,
    height: 41,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  verTudoText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  cardTitleText: {
    fontSize: 11,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  dropText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  voltarBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  voltarText: {
    fontSize: 15,
    fontWeight: 'bold',
  },
});
