import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  contentScroll: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  emptyContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 16,
    color: '#919191',
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E3E4EB',
    borderRadius: 15,
    height: 110,
    marginBottom: 10,
    overflow: 'hidden',
  },
  productPhoto: {
    width: 90,
    height: 90,
    marginLeft: 8,
    borderRadius: 8,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  colSep: {
    width: 1.5,
    height: '100%',
    backgroundColor: '#F5F5F5',
  },
  colInfo: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    gap: 8,
  },
  colHeader: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
  },
  colValue: {
    fontSize: 11,
    color: '#000000',
    textAlign: 'center',
  },
  colQty: {
    width: 75,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  qtyNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
  },
  buttonsContainer: {
    position: 'absolute',
    bottom: 115,
    left: 0,
    right: 0,
    alignItems: 'center',
    gap: 10,
  },
  buttonsRow: {
    flexDirection: 'row',
    gap: 14,
  },
  btnContinuar: {
    width: 160,
    height: 65,
    borderRadius: 15,
    backgroundColor: '#E3E4EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnProsseguir: {
    width: 160,
    height: 65,
    borderRadius: 15,
    backgroundColor: '#2A7420',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnPedidos: {
    width: 220,
    height: 65,
    borderRadius: 15,
    backgroundColor: '#1C2434',
    alignItems: 'center',
    justifyContent: 'center',
  },
  meuCarrinhoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  removerBtnContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: 140,
    height: 42,
    borderRadius: 21,
    paddingHorizontal: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  cartRemoveIconWrapper: {
    position: 'relative',
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartMinusBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
  },
  removerBtnText: {
    color: '#FF3B30',
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 6,
  },
  btnTextPrimary: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  btnTextSecondary: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  editControlsContainer: {
    alignItems: 'flex-end',
    gap: 6,
  },
  buttonsRowHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  cancelBtn: {
    backgroundColor: '#FF3B30',
    width: 90,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  removerColumn: {
    alignItems: 'center',
    position: 'relative',
  },
  selectAllBtn: {
    position: 'absolute',
    top: 45,
    alignSelf: 'center',
  },
  selectAllText: {
    color: '#8B0000',
    fontWeight: 'bold',
    fontSize: 14,
  },
  qtyEditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  decreaseBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0.5 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  qtyNumberEdit: {
    fontSize: 16,
    fontWeight: 'bold',
    minWidth: 16,
    textAlign: 'center',
  },
  checkboxTouchTarget: {
    padding: 4,
  },
  checkboxContainer: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#888',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  checkboxSelected: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  removedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 15,
    alignSelf: 'center',
    width: '100%',
  },
  removedBannerText: {
    fontSize: 13,
    fontWeight: 'bold',
    flexShrink: 1,
  },
});

export default styles;
