import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: '#F5F5F5' },
  filterContainer: { backgroundColor: '#F5F5F5', paddingHorizontal: 8, paddingVertical: 8, alignItems: 'center' },
  filterPill: { flexDirection: 'row', borderRadius: 30, paddingHorizontal: 14, paddingVertical: 10, alignItems: 'center', gap: 10, width: '95%', alignSelf: 'center' },
  filterBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  filterSep: { width: 1, height: 20, backgroundColor: '#8A7268' },
  filterBtnText: { fontSize: 12, fontWeight: 'bold', marginLeft: 2 },
  categoryLabelText: { fontSize: 12, fontWeight: 'bold' },
  categoriesRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingRight: 10 },
  tagItem: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12 },
  tagText: { fontSize: 12 },
  actionButtonsRow: { flexDirection: 'row', paddingHorizontal: 12, justifyContent: 'space-between', gap: 10, marginBottom: 10, marginTop: 2 },
  registerBtn: { width: '100%', flexDirection: 'row', backgroundColor: '#339914', paddingVertical: 6, paddingHorizontal: 8, borderRadius: 15, alignItems: 'center', justifyContent: 'center', gap: 6, height: 46 },
  massDeleteBtn: { width: '100%', flexDirection: 'row', backgroundColor: '#A72424', paddingVertical: 6, paddingHorizontal: 8, borderRadius: 15, alignItems: 'center', justifyContent: 'center', gap: 6, height: 46 },
  massDeleteBtnActive: { backgroundColor: '#7A1A1A' },
  massDeleteBtnText: { color: '#FFF', fontWeight: 'bold', fontSize: 15 },
  deleteColumnContainer: { flex: 1, flexDirection: 'column', alignItems: 'center' },
  actionBtnText: { color: '#FFFFFF', fontSize: 15, fontWeight: 'bold', marginLeft: 4 },
  productsList: { paddingHorizontal: 12, paddingBottom: 20 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingTop: 60 },
  emptyText: { color: '#767676', fontSize: 16 },
  productCard: { backgroundColor: '#E3E4EB', borderRadius: 15, minHeight: 100, marginBottom: 12, position: 'relative', justifyContent: 'center' },
  cardInactive: { opacity: 0.5 },
  selectedCard: { borderWidth: 2, borderColor: '#F97D01' },
  cardRow: { flexDirection: 'row', alignItems: 'center', height: 100, paddingRight: 30 },
  checkboxArea: { marginLeft: 6, marginRight: 4 },
  checkbox: { width: 20, height: 20, borderRadius: 4, borderWidth: 1.2, borderColor: '#A72424', alignItems: 'center', justifyContent: 'center' },
  checkboxChecked: { backgroundColor: '#A72424' },
  checkmark: { color: '#FFF', fontWeight: 'bold', fontSize: 13 },
  productImageWrapper: { width: 82, height: 82, borderRadius: 8, overflow: 'hidden', backgroundColor: '#FFFFFF', marginLeft: 10, marginRight: 4 },
  productImage: { width: '100%', height: '100%' },
  noImage: { justifyContent: 'center', alignItems: 'center' },
  noImageText: { color: '#919191', fontSize: 10, textAlign: 'center' },
  nameColumn: { flex: 1, alignItems: 'center', justifyContent: 'flex-start', paddingHorizontal: 4, paddingTop: 4, height: '100%' },
  columnHeader: { fontSize: 12, color: '#1C2434', textAlign: 'center', fontWeight: 'bold', marginBottom: 8 },
  productName: { fontSize: 12, color: '#1C2434', textAlign: 'center' },
  quantityColumn: { flex: 0.8, alignItems: 'center', justifyContent: 'flex-start', paddingHorizontal: 2, paddingTop: 4, height: '100%' },
  quantityValue: { fontSize: 24, color: '#1C2434', marginTop: 6 },
  statusColumn: { flex: 0.8, alignItems: 'center', justifyContent: 'flex-start', paddingHorizontal: 2, paddingTop: 4, height: '100%' },
  editIconBtn: { position: 'absolute', top: -8, right: -8, zIndex: 10, padding: 6 },
  trashIconBtn: { position: 'absolute', bottom: -8, right: -8, zIndex: 10, padding: 6 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  whiteModalContainer: { borderRadius: 20, padding: 24, width: '85%', alignSelf: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 5 },
  whiteModalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 12, textAlign: 'center' },
  modalSubsectionHeader: { fontSize: 13, fontWeight: 'bold', textTransform: 'uppercase', marginTop: 10, marginBottom: 6 },
  modalButtonsRow: { flexDirection: 'row', gap: 10, marginTop: 20 },
  modalConfirmBtn: { flex: 1.5, paddingVertical: 12, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  modalConfirmText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 14 },
  modalCancelBtn: { flex: 1, paddingVertical: 12, borderRadius: 10, borderWidth: 1.2, alignItems: 'center', justifyContent: 'center' },
  modalCancelText: { fontWeight: 'bold', fontSize: 14 },
  secondaryActionsRow: { flexDirection: 'row', paddingHorizontal: 12, justifyContent: 'space-between', gap: 10, marginBottom: 10, marginTop: 4 },
  secondaryBtn: { flex: 1, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 1, elevation: 1 },
  secondaryBtnText: { fontWeight: 'bold', fontSize: 13 },
});
