import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  subHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#E8E9F0',
  },
  subHeaderLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#767676',
  },
  subHeaderValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1C2434',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
  },
  statusCard: {
    minHeight: 160,
    borderRadius: 16,
    marginBottom: 12,
    paddingVertical: 30,
    paddingHorizontal: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  statusTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1C2434',
    textAlign: 'center',
    marginBottom: 40,
  },
  trackContainer: {
    height: 4,
    justifyContent: 'center',
    position: 'relative',
    marginHorizontal: 15,
  },
  baseLine: {
    height: 4,
    borderRadius: 2,
    width: '100%',
    position: 'absolute',
  },
  glowLine: {
    height: 12,
    borderRadius: 6,
    width: '100%',
    position: 'absolute',
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
    elevation: 4,
  },
  circleOuter: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  circleInner: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 3,
    backgroundColor: '#FFFFFF',
  },
  statusTextRow: {
    flexDirection: 'row',
    marginTop: 18,
    marginHorizontal: 10,
  },
  statusLabelText: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  sectionListTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1C2434',
    marginBottom: 12,
    marginLeft: 4,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 80,
    gap: 12,
  },
  emptyText: {
    fontSize: 14,
    color: '#767676',
    textAlign: 'center',
  },
  productCard: {
    flexDirection: 'row',
    borderRadius: 15,
    marginBottom: 14,
    padding: 12,
    backgroundColor: '#E3E4EB',
    overflow: 'hidden',
  },
  photoContainer: {
    width: 90,
    height: 90,
    borderRadius: 10,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 12,
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  placeholderImage: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EAEAEA',
  },
  infoContainer: {
    flex: 1,
    justifyContent: 'center',
    gap: 4,
  },
  productName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1C2434',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 4,
  },
  qtyBadge: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: '#D4D5DC',
  },
  qtyText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1C2434',
  },
  unitPrice: {
    fontSize: 12,
    color: '#767676',
  },
  dateContainer: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 12,
  },
  dateText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#767676',
  },
  clientCard: {
    borderRadius: 16,
    marginTop: 8,
    marginBottom: 12,
    paddingVertical: 18,
    paddingHorizontal: 20,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  clientCardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1C2434',
    marginBottom: 14,
  },
  clientRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
    gap: 8,
  },
  clientLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#767676',
  },
  clientValue: {
    flex: 1,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1C2434',
  },
  totalCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 16,
    marginBottom: 16,
    paddingVertical: 18,
    paddingHorizontal: 20,
    backgroundColor: '#FAFAFA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1C2434',
  },
  totalValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#339914',
  },
  voltarBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    marginTop: 15,
    marginBottom: 20,
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  voltarText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1C2434',
  },
});
