import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'ios' ? 54 : StatusBar.currentHeight ? StatusBar.currentHeight + 10 : 40,
    paddingBottom: 16,
    paddingHorizontal: 16,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  subHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  subHeaderLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  subHeaderValue: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 180,
  },
  statusCard: {
    minHeight: 160,
    borderRadius: 16,
    marginBottom: 12,
    paddingVertical: 30,
    paddingHorizontal: 20,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  statusTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 40,
  },
  trackContainer: {
    height: 4,
    justifyContent: 'center',
    position: 'relative',
    marginHorizontal: 15,
  },
  baseLine: {
    height: 4,
    borderRadius: 2,
    width: '100%',
    position: 'absolute',
  },
  glowLine: {
    height: 12,
    borderRadius: 6,
    width: '100%',
    position: 'absolute',
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
    elevation: 4,
  },
  circleOuter: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  circleInner: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 3,
    backgroundColor: '#FFFFFF',
  },
  statusTextRow: {
    flexDirection: 'row',
    marginTop: 18,
    marginHorizontal: 10,
  },
  statusLabelText: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  dateContainer: {
    alignItems: 'center',
    marginBottom: 25,
  },
  dateText: {
    fontSize: 14,
    fontWeight: '500',
  },
  sectionListTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
    marginLeft: 4,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 80,
    gap: 12,
  },
  emptyText: {
    fontSize: 14,
    textAlign: 'center',
  },
  productCard: {
    flexDirection: 'row',
    borderRadius: 15,
    marginBottom: 14,
    padding: 12,
    overflow: 'hidden',
  },
  photoContainer: {
    width: 90,
    height: 90,
    borderRadius: 10,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  placeholderImage: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContainer: {
    flex: 1,
    justifyContent: 'center',
    gap: 4,
  },
  productName: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  productDescription: {
    fontSize: 12,
    lineHeight: 16,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 4,
  },
  qtyBadge: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 8,
  },
  qtyText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  unitPrice: {
    fontSize: 12,
  },
  subtotal: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 2,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopWidth: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerContent: {
    gap: 2,
  },
  totalLabel: {
    fontSize: 12,
  },
  totalValue: {
    fontSize: 22,
    fontWeight: 'bold',
  },
  footerBackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  footerBackText: {
    fontSize: 15,
    fontWeight: 'bold',
  },
});
