import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const CARD_PADDING = 16;
const CARD_INNER = SCREEN_WIDTH - 32 - (CARD_PADDING * 2);

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  contentScroll: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 110,
  },
  productCard: {
    backgroundColor: '#E3E4EB',
    borderRadius: 25,
    padding: CARD_PADDING,
    marginBottom: 16,
  },
  topRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  photoWrapper: {
    width: CARD_INNER * 0.48,
    aspectRatio: 159 / 215,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  infoColumn: {
    flex: 1,
    paddingLeft: 12,
    justifyContent: 'flex-start',
    paddingTop: 4,
  },
  productTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1C2434',
    textAlign: 'center',
    marginBottom: 16,
  },
  productSubtitle: {
    fontSize: 14,
    color: '#1C2434',
    textAlign: 'center',
  },
  infoEmbalagem: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#1C2434',
    textAlign: 'center',
    lineHeight: 24,
  },
  descricaoText: {
    fontSize: 13,
    color: '#1C2434',
    textAlign: 'center',
    marginBottom: 6,
  },
  precoText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1C2434',
    textAlign: 'center',
    marginBottom: 12,
  },
  cartSection: {
    position: 'relative',
    marginTop: 4,
  },
  cartBigBtn: {
    position: 'absolute',
    left: 0,
    top: -10,
    width: 69,
    height: 69,
    borderRadius: 25,
    backgroundColor: '#1C2434',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  cartPlusBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#435270',
    borderRadius: 20,
    height: 50,
    paddingLeft: 12,
    paddingRight: 12,
  },
  quantityLabel: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '500',
    marginLeft: 4,
  },
  quantitySep: {
    width: 1,
    height: 35,
    backgroundColor: 'rgba(255,255,255,0.3)',
    marginHorizontal: 8,
  },
  quantityControls: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  btnMinus: {
    width: 23,
    height: 23,
    borderRadius: 2,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  minusLine: {
    width: 12,
    height: 2.5,
    backgroundColor: '#C41919',
  },
  quantityNum: {
    width: 30,
    height: 30,
    borderRadius: 2,
    backgroundColor: '#1A1A1A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityNumText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  btnPlus: {
    width: 23,
    height: 23,
    borderRadius: 2,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  plusLineH: {
    position: 'absolute',
    width: 12,
    height: 2.5,
    backgroundColor: '#25BE36',
  },
  plusLineV: {
    position: 'absolute',
    width: 2.5,
    height: 12,
    backgroundColor: '#25BE36',
  },
  relatedTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1C2434',
    marginBottom: 12,
  },
  relatedScroll: {
    gap: 12,
    paddingBottom: 20,
  },
  relatedCard: {
    backgroundColor: '#E3E4EB',
    borderRadius: 20,
    paddingTop: 8,
    paddingHorizontal: 8,
    paddingBottom: 10,
    width: 170,
  },
  relatedPhotoBox: {
    width: 154,
    height: 110,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
    marginBottom: 6,
  },
  relatedPhotoPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  relatedInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  relatedCartCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E3DAD9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  relatedTexts: {
    flex: 1,
  },
  relatedName: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#1C2434',
  },
  relatedPrice: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#1C2434',
  },
  bottomBarOuter: {
    position: 'absolute',
    bottom: 10,
    left: 16,
    right: 16,
  },
  bottomBarInner: {
    flexDirection: 'row',
    backgroundColor: '#E3E4EB',
    borderRadius: 30,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  tabSep: {
    width: 1,
    height: 49,
    backgroundColor: '#8A7268',
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  iconBg: {
    width: 51,
    height: 41,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBgActive: {
    width: 51,
    height: 41,
    borderRadius: 20,
    backgroundColor: '#E3DAD9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  relatedPhoto: {
    width: 154,
    height: 110,
    borderRadius: 15,
  },
  noRelatedText: {
    fontSize: 14,
    fontStyle: 'italic',
    textAlign: 'center',
    marginVertical: 20,
    paddingHorizontal: 16,
  },
});

export { styles };
